---
#
#  Ansible Tower looks in collections/requirements.yml for collections to install
#
collections:
    #
    # Install collection(s) from Ansible Galaxy.
    #
  - name: cisco.nxos
    source: https://galaxy.ansible.com
    version: 3.1.0
  - name: ansible.netcommon
    source: https://galaxy.ansible.com
    version: 3.0.1
